on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

name: Conformance
jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout conformance client
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run test suite
        uses: theupdateframework/tuf-conformance@dee4e23533d7a12a6394d96b59b3ea0aa940f9bf # v2.2.0
        with:
          entrypoint: ".github/scripts/conformance-client.py"
