name: Scorecards analysis
on:
  branch_protection_rule:
  schedule:
    - cron: '21 6 * * 1'
  push:
    branches: [ develop ]
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      # NOTE: If you add security critical permissions, start pinning used actions
      security-events: write # for uploading to code-scanning dashboard
      id-token: write # for publishing results in scorecard public dataset
      actions: read
      contents: read

    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Run analysis"
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: results.sarif
          # sarif format required by upload-sarif action
          results_format: sarif
          # "repo_token" not set because personal access tokens are dangerous.
          # This means Branch-Protection check will not have correct results.
          publish_results: true

      - name: "Upload to code-scanning dashboard"
        uses: github/codeql-action/upload-sarif@v3  # unpinned since this is not security critical
        with:
          sarif_file: results.sarif
